-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-18 17:33:01 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
SET ECHO ON
SPOOL 'wc_schema_output.txt'

DROP TABLE address CASCADE CONSTRAINTS;

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE port_temp CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE stop CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    address_street   VARCHAR2(100) NOT NULL,
    address_town     VARCHAR2(85) NOT NULL,
    address_postcode VARCHAR2(20) NOT NULL,
    address_country  VARCHAR2(60) NOT NULL
);

COMMENT ON COLUMN address.address_street IS
    'Address''s street';

COMMENT ON COLUMN address.address_town IS
    'Address''s town';

COMMENT ON COLUMN address.address_postcode IS
    'Address''s postcode';

COMMENT ON COLUMN address.address_country IS
    'Address''s country';

ALTER TABLE address
    ADD CONSTRAINT address_pk PRIMARY KEY ( address_street,
                                            address_town,
                                            address_postcode,
                                            address_country );

CREATE TABLE cabin (
    cab_no       VARCHAR2(3) NOT NULL,
    cab_capacity NUMBER(1) NOT NULL,
    cab_class    CHAR(1) NOT NULL,
    ship_code    NUMBER(5) NOT NULL
);

ALTER TABLE cabin
    ADD CONSTRAINT chk_cab_class CHECK ( cab_class IN ( 'B', 'I', 'O', 'S' ) );

COMMENT ON COLUMN cabin.cab_no IS
    'Cabin number';

COMMENT ON COLUMN cabin.cab_capacity IS
    'Cabin''s capacity';

COMMENT ON COLUMN cabin.cab_class IS
    'Cabin''s class';

COMMENT ON COLUMN cabin.ship_code IS
    'Ship Code';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cab_no,
                                                        ship_code );

CREATE TABLE country (
    country_code CHAR(2) NOT NULL,
    country_name VARCHAR2(60) NOT NULL,
    port_code    NUMBER(4) NOT NULL
);

COMMENT ON COLUMN country.country_code IS
    'Country code';

COMMENT ON COLUMN country.country_name IS
    'Country name';

COMMENT ON COLUMN country.port_code IS
    'Port code';

CREATE UNIQUE INDEX country__idx ON
    country (
        port_code
    ASC );

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE cruise (
    cruise_id   NUMBER(4) NOT NULL,
    cruise_name VARCHAR2(35) NOT NULL,
    cruise_desc VARCHAR2(200) NOT NULL,
    ship_code   NUMBER(5) NOT NULL
);

COMMENT ON COLUMN cruise.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN cruise.cruise_name IS
    'Cruise name';

COMMENT ON COLUMN cruise.cruise_desc IS
    'Description of cruise';

COMMENT ON COLUMN cruise.ship_code IS
    'Ship Code';

ALTER TABLE cruise ADD CONSTRAINT cruise_pk PRIMARY KEY ( cruise_id );

CREATE TABLE manifest (
    boarding_time DATE NOT NULL,
    cab_no        VARCHAR2(3) NOT NULL,
    ship_code     NUMBER(5) NOT NULL,
    cruise_id     NUMBER(4) NOT NULL,
    passenger_id  NUMBER(5) NOT NULL,
    cruise_id1    NUMBER(4) NOT NULL
);

COMMENT ON COLUMN manifest.boarding_time IS
    'Time a passenger boards on a ship';

COMMENT ON COLUMN manifest.cab_no IS
    'Cabin number';

COMMENT ON COLUMN manifest.ship_code IS
    'Ship Code';

COMMENT ON COLUMN manifest.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN manifest.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN manifest.cruise_id1 IS
    'Cruise ID';

ALTER TABLE manifest
    ADD CONSTRAINT manifest_pk PRIMARY KEY ( cruise_id,
                                             passenger_id,
                                             cruise_id1 );

CREATE TABLE operator (
    op_id           NUMBER(4) NOT NULL,
    op_company_name VARCHAR2(50) NOT NULL,
    op_ceo_name     VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN operator.op_id IS
    'Operator ID';

COMMENT ON COLUMN operator.op_company_name IS
    'Operator''s company name';

COMMENT ON COLUMN operator.op_ceo_name IS
    'Operator''s company CEO name';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( op_id );

CREATE TABLE passenger (
    passenger_id             NUMBER(5) NOT NULL,
    passenger_fname          VARCHAR2(20) NOT NULL,
    passenger_lname          VARCHAR2(20) NOT NULL,
    passenger_gender         CHAR(1) NOT NULL,
    passenger_dob            DATE NOT NULL,
    passenger_lang           CHAR(2),
    passenger_cruise_payment CHAR(1) NOT NULL,
    cruise_id                NUMBER(4) NOT NULL,
    address_street           VARCHAR2(100) NOT NULL,
    address_town             VARCHAR2(85) NOT NULL,
    address_postcode         VARCHAR2(20) NOT NULL,
    address_country          VARCHAR2(60) NOT NULL,
    passenger_id1            NUMBER(5),
    cruise_id1               NUMBER(4)
);

ALTER TABLE passenger
    ADD CONSTRAINT chk_passenger_gender CHECK ( passenger_gender IN ( 'F', 'M' ) );

ALTER TABLE passenger
    ADD CONSTRAINT chk_passenger_cruise_payment CHECK ( passenger_cruise_payment IN (
    'N', 'Y' ) );

COMMENT ON COLUMN passenger.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.passenger_fname IS
    'Passenger''s first name';

COMMENT ON COLUMN passenger.passenger_lname IS
    'Passenger''s last name';

COMMENT ON COLUMN passenger.passenger_gender IS
    'Passenger''s gender';

COMMENT ON COLUMN passenger.passenger_dob IS
    'Passenger''s date of birth';

COMMENT ON COLUMN passenger.passenger_lang IS
    'Passenger''s language';

COMMENT ON COLUMN passenger.passenger_cruise_payment IS
    'Passenger''s cruise payment';

COMMENT ON COLUMN passenger.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN passenger.address_street IS
    'Address''s street';

COMMENT ON COLUMN passenger.address_town IS
    'Address''s town';

COMMENT ON COLUMN passenger.address_postcode IS
    'Address''s postcode';

COMMENT ON COLUMN passenger.address_country IS
    'Address''s country';

COMMENT ON COLUMN passenger.passenger_id1 IS
    'Passenger ID';

COMMENT ON COLUMN passenger.cruise_id1 IS
    'Cruise ID';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( passenger_id,
                                                                cruise_id );

CREATE TABLE port (
    port_code       NUMBER(4) NOT NULL,
    port_name       VARCHAR2(50) NOT NULL,
    port_country    VARCHAR2(60) NOT NULL,
    port_population NUMBER(5),
    port_longitude  NUMBER(10, 7),
    port_latitude   NUMBER(10, 7),
    country_code    CHAR(2) NOT NULL
);

COMMENT ON COLUMN port.port_code IS
    'Port code';

COMMENT ON COLUMN port.port_name IS
    'Port name';

COMMENT ON COLUMN port.port_country IS
    'Port country';

COMMENT ON COLUMN port.port_population IS
    'Port population';

COMMENT ON COLUMN port.port_longitude IS
    'Port''s longitude';

COMMENT ON COLUMN port.port_latitude IS
    'Port''s latitude';

COMMENT ON COLUMN port.country_code IS
    'Country code';

CREATE UNIQUE INDEX port__idx ON
    port (
        country_code
    ASC );

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE port_temp (
    port_temp_month        CHAR(3) NOT NULL,
    port_temp_average_high NUMBER(2) NOT NULL,
    port_temp_average_low  NUMBER(2) NOT NULL,
    port_code              NUMBER(4) NOT NULL
);

COMMENT ON COLUMN port_temp.port_temp_month IS
    'Port''s temperature in a particular month';

COMMENT ON COLUMN port_temp.port_temp_average_high IS
    'Port''s average high temperature';

COMMENT ON COLUMN port_temp.port_temp_average_low IS
    'Port''s average low temperature';

COMMENT ON COLUMN port_temp.port_code IS
    'Port code';

ALTER TABLE port_temp ADD CONSTRAINT port_temp_pk PRIMARY KEY ( port_temp_month );

CREATE TABLE ship (
    ship_code        NUMBER(5) NOT NULL,
    ship_name        VARCHAR2(35) NOT NULL,
    ship_comm_date   DATE NOT NULL,
    ship_tonnage     NUMBER(6) NOT NULL,
    ship_max_cap     NUMBER(4) NOT NULL,
    ship_reg_country VARCHAR2(30),
    op_id            NUMBER(4) NOT NULL
);

COMMENT ON COLUMN ship.ship_code IS
    'Ship Code';

COMMENT ON COLUMN ship.ship_name IS
    'Name of ship';

COMMENT ON COLUMN ship.ship_comm_date IS
    'Date of ship commissioned';

COMMENT ON COLUMN ship.ship_tonnage IS
    'Tonnage of the ship';

COMMENT ON COLUMN ship.ship_max_cap IS
    'Maximum capacity of the ship';

COMMENT ON COLUMN ship.ship_reg_country IS
    'Ship registered country';

COMMENT ON COLUMN ship.op_id IS
    'Operator ID';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE stop (
    port_code           NUMBER(4) NOT NULL,
    cruise_id           NUMBER(4) NOT NULL,
    stop_datetime       DATE NOT NULL,
    stop_departorarrive CHAR(1) NOT NULL,
    stop_id             NUMBER(5) NOT NULL
);

ALTER TABLE stop
    ADD CONSTRAINT chk_stop_departorarrive CHECK ( stop_departorarrive IN ( 'N', 'Y' ) );

COMMENT ON COLUMN stop.port_code IS
    'Port code';

COMMENT ON COLUMN stop.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN stop.stop_datetime IS
    'Stop date and time';

COMMENT ON COLUMN stop.stop_departorarrive IS
    'Depart or arrive in stop';

COMMENT ON COLUMN stop.stop_id IS
    'Surrogate key';

ALTER TABLE stop ADD CONSTRAINT stop_pk PRIMARY KEY ( stop_id );

ALTER TABLE stop ADD CONSTRAINT stop_nk UNIQUE ( port_code,
                                                 cruise_id );

CREATE TABLE tour (
    tour_no                 NUMBER(5) NOT NULL,
    tour_name               VARCHAR2(50) NOT NULL,
    tour_desc               VARCHAR2(200) NOT NULL,
    tour_hours_required     NUMBER(2) NOT NULL,
    tour_cost_per_person    NUMBER(5) NOT NULL,
    tour_wheel_chair_access CHAR(1) NOT NULL,
    tour_availability       CHAR(1) NOT NULL,
    tour_start_time         DATE NOT NULL,
    tour_date               DATE NOT NULL,
    port_code               NUMBER(4) NOT NULL
);

ALTER TABLE tour
    ADD CONSTRAINT chk_tour_wheel_chair_access CHECK ( tour_wheel_chair_access IN ( 'N',
    'Y' ) );

ALTER TABLE tour
    ADD CONSTRAINT chk_tour_availability CHECK ( tour_availability IN ( 'N', 'Y' ) );

COMMENT ON COLUMN tour.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour.tour_name IS
    'Tour name';

COMMENT ON COLUMN tour.tour_desc IS
    'Tour description';

COMMENT ON COLUMN tour.tour_hours_required IS
    'Hours required for tour';

COMMENT ON COLUMN tour.tour_cost_per_person IS
    'Tour cost per person';

COMMENT ON COLUMN tour.tour_wheel_chair_access IS
    'Tour''s wheel chair access';

COMMENT ON COLUMN tour.tour_availability IS
    'Tour''s availability';

COMMENT ON COLUMN tour.tour_start_time IS
    'Tour''s starting time';

COMMENT ON COLUMN tour.tour_date IS
    'Tour''s date';

COMMENT ON COLUMN tour.port_code IS
    'Port code';

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_no,
                                                      port_code );

ALTER TABLE passenger
    ADD CONSTRAINT address_passenger FOREIGN KEY ( address_street,
                                                   address_town,
                                                   address_postcode,
                                                   address_country )
        REFERENCES address ( address_street,
                             address_town,
                             address_postcode,
                             address_country );

ALTER TABLE manifest
    ADD CONSTRAINT cabin_manifest FOREIGN KEY ( cab_no,
                                                ship_code )
        REFERENCES cabin ( cab_no,
                           ship_code );

ALTER TABLE manifest
    ADD CONSTRAINT cruise_manifest FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE passenger
    ADD CONSTRAINT cruise_passenger FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE stop
    ADD CONSTRAINT cruise_stop FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE manifest
    ADD CONSTRAINT manifest_passenger FOREIGN KEY ( passenger_id,
                                                    cruise_id1 )
        REFERENCES passenger ( passenger_id,
                               cruise_id );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( op_id )
        REFERENCES operator ( op_id );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_guardian FOREIGN KEY ( passenger_id1,
                                                    cruise_id1 )
        REFERENCES passenger ( passenger_id,
                               cruise_id );

ALTER TABLE country
    ADD CONSTRAINT port_country FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE port
    ADD CONSTRAINT port_countryv1 FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE port_temp
    ADD CONSTRAINT port_porttemp FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE stop
    ADD CONSTRAINT port_stop FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE tour
    ADD CONSTRAINT port_tour FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE cabin
    ADD CONSTRAINT ship_cabin FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE cruise
    ADD CONSTRAINT ship_cruise FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

SPOOL OFF
SET ECHO OFF

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             2
-- ALTER TABLE                             34
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
